### ISSUE TITLE
알바 이슈

### ISSUE THREAD

**Issue by HyunwooisMikeSteven** [team-peekabook/Peekabook-Gidi#31]
MS = '알바'
condition = '귀찮음'
solution = input("알바를 째시겠습니까?")

if solution == '네' :
    print("너 해고")
else:
    print("귀찮음 2스택")
    
print("바비브로스 버거 먹고싶다")

**Comment by ziwoohan** [comment]
일이나 해

**Comment by stockton66785** [comment]
해라나 일
