### ISSUE TITLE
이현우(기획)씨 머리 부딪힘 이슈

### ISSUE THREAD

**Issue by ziwoohan** [team-peekabook/Peekabook-Gidi#5]
모두들 쇼파 위에 올라갈 때는 머리 위를 조심하세요!

**Comment by 6uohul** [comment]
아프지마 도토도토잠보

**Comment by stockton66785** [comment]
> 모두들 쇼파 위에 올라갈 때는 머리 위를 조심하세요!

코드리뷰 해드리러 왔습니다. 제 점수는요 5점 만점에 4.6점 드립니다. 
이상 코드 평론가 문동진이었습니다
